name = input('请输入你姓名')
ago = input('请输入你的年龄')
sex = input('请输入你的性别')
high = float(input('请输入你的身高'))
weight = float(input('请输入你的体重'))
ID_number = int(input('请输入你的身份证号码'))
print('*'*20)
print('姓名%s\n年龄%s\n身高%f'%(name,ago,high))
print('*'*20)
