#print('*'*20)
name = input('请输入姓名')
sex = input('请输入性别')
phone = input('请输入电话号码')
addr = input('请输入家庭住址')
email = input('请输入邮箱地址')
#print('姓名%s\n'%name.'性别%s\n'%sex,'电话：%s\n'%phone)
print('*'*20)
print('姓名%s\n性别%s\n电话%s\n家庭住址%s\n邮箱是%s\n'%(name,sex,phone,addr,email))
print('*'*20)

